### ISSUE TITLE
Can you publish this module to NPM?

### ISSUE THREAD

**Issue by wolfeidau** [cujojs/most-w3msg#5]
Just started using this module for a small app I am building and really like how it works, however i have to pull it into my project.

Would be great to have this in NPM.

Thanks!

**Comment by briancavalier** [comment]
Hey @wolfeidau, thanks for the nudge :)

There are a couple simple things we'll need to do before publishing it:

1. make sure it works with the latest most.js (0.13.x as of right now)
2. decide whether the `to*` functions are the right approach ... they work well, but I'm wondering if there's a better way.  Do you plan to use these, or just the `from*` functions?

I can probably spend a little time this week to get it ready to publish.

**Comment by wolfeidau** [comment]
Gday @briancavalier.

Here is the prototype i am using the library in at the moment.

https://github.com/wolfeidau/sysinfo-ui/blob/master/app/index.jsx#L6-L8

Just learning react at the moment, my aim is to try and remove all state from the ui using `most`.

Still trying to figure out the best way to have more than one component consuming the "stream", at the moment it goes into the parent and children are informed of the changes.

Thanks

**Comment by briancavalier** [comment]
Cool!  I did a small demo with react + most + stomp over websocket a while back.  It's a bit outdated (uses a much older version of most), but might be interesting.  The [react component (Scoreboard)](https://github.com/briancavalier/scores/blob/rave-most-react/src/main/resources/public/Scoreboard.jsx) expects to be [given a stream to consume when an instance is created](https://github.com/briancavalier/scores/blob/rave-most-react/src/main/resources/public/main.js#L24)

**Comment by wolfeidau** [comment]
Yeah nice work.

Do you have any suggestions on how to take a feed of events and demux them out to different components using most?

There are a few examples which filter, but very little on demuxing those filtered events out to many streams. In my case I have an aggregate event containing metrics, which i want to slice up and pass to many components.

Anyway I will keep exploring most and hacking on this project as it is very interesting!

Cheers

**Comment by briancavalier** [comment]
> Do you have any suggestions on how to take a feed of events and demux them out to different components using most?

The simplest thing that comes is to use `stream.filter` to create new streams containing what you need.  Since streams are immutable, filtering a stream creates a new stream containing only the elements matching the predicate, and leaves the original stream intact.  For example:

```js
let original = most.from([1, 2, 3, 4, 5, 6, 7, 8, 9]);
let evens = original.filter(x => x % 2 === 0); // 2,4,6,8
let odds = original.filter(x => x % 2 !== 0); // 1,3,5,7,9
let lessThan5 = original.filter(x => x < 5); // 1,2,3,4
// original is still 1,2,3,4,5,6,7,8,9
```

Does that help?

**Comment by wolfeidau** [comment]
Mate that is fantastic!

Exactly what I was after, lets me build a dashboard that is effectively stateless, which is what I was aiming for.

Thanks for your help!

**Comment by briancavalier** [comment]
Keep an eye on #6 :) Once unit tests get merged, I think we can publish to npm.

**Comment by unscriptable** [comment]
Hey @wolfeidau, any chance you could update your README to mention most.js?  We'd be very grateful for the exposure! :)

**Comment by briancavalier** [comment]
Published! [Here it is](https://www.npmjs.com/package/most-w3msg)

**Comment by wolfeidau** [comment]
@unscriptable done.

@briancavalier cheers for sorting this out :+1: 

I am slowly getting my head around how to use the streams you illustrated, will take a bit for all these new tools to become a bit more natural.

Thanks again

**Comment by briancavalier** [comment]
@wolfeidau You bet, and thanks for adding most.js to your README.

**Comment by unscriptable** [comment]
Thanks, @wolfeidau!
